import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';
import { defineConfig } from 'vitest/config';

// Mirrors the path aliases generated by SvelteKit in .svelte-kit/tsconfig.json.
// We can't inherit vite.config.ts (it uses the `sveltekit()` plugin which
// requires a full SvelteKit server context and crashes under Vitest 4).
// Instead we use the bare `svelte()` plugin and replicate aliases here.
const root = resolve(__dirname, 'src');

export default defineConfig({
	plugins: [svelte()],
	resolve: {
		alias: {
			$lib: resolve(root, 'lib'),
			'$lib/*': resolve(root, 'lib/*'),
			$features: resolve(root, 'lib/features'),
			'$features/*': resolve(root, 'lib/features/*'),
			$layouts: resolve(root, 'lib/layouts'),
			'$layouts/*': resolve(root, 'lib/layouts/*'),
			$ui: resolve(root, 'lib/components/ui'),
			'$ui/*': resolve(root, 'lib/components/ui/*'),
			$form: resolve(root, 'lib/components/form'),
			'$form/*': resolve(root, 'lib/components/form/*'),
			$icons: resolve(root, 'lib/icons'),
			'$icons/*': resolve(root, 'lib/icons/*'),
			$api: resolve(root, 'lib/api'),
			'$api/*': resolve(root, 'lib/api/*'),
			// SvelteKit virtual modules — stubbed via `vi.mock(...)` in
			// individual tests but vite still needs a resolvable alias
			// during import-analysis. Empty stubs at known paths satisfy
			// that without affecting test behaviour.
			'$app/navigation': resolve(__dirname, 'tests/unit/stubs/app-navigation.ts'),
			'$app/state': resolve(__dirname, 'tests/unit/stubs/app-state.ts')
		}
	},
	test: {
		environment: 'jsdom',
		setupFiles: ['./tests/unit/setup.ts'],
		include: ['tests/unit/**/*.test.ts', 'src/**/*.test.ts'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html', 'lcov', 'json-summary'],
			reportsDirectory: './coverage',
			include: ['src/**/*.{ts,svelte}'],
			exclude: [
				'src/app.html',
				'src/app.d.ts',
				'src/hooks.client.ts',
				'src/lib/i18n/locales/**',
				'src/styles/**',
				'**/*.test.ts',
				'**/*.spec.ts',
				// Storybook stories — render-only, no logic to test
				'**/*.stories.{ts,svelte}',
				// Feature barrels — pure re-export shells, no testable behaviour
				'src/lib/features/*/index.ts',
				'src/lib/features/*/*/index.ts',
				'src/lib/components/**/index.ts',
				'src/lib/hooks/index.ts',
				'src/lib/icons/index.ts'
			],
			// Coverage thresholds — re-ratcheted 2026-05-25 to the measured
			// floor after the CRM module rollout, primitive expansion, and
			// Wave-1/Wave-2 architecture-test work. The denominator grew
			// ~60% (8.8k → 13.2k source lines) without proportional unit-
			// test growth because:
			//   - Svelte components + TanStack query hooks require jsdom +
			//     SvelteKit mock scaffolding (Phase F work).
			//   - E2E suite (133 Playwright tests) covers the route-level
			//     happy paths the unit suite would otherwise duplicate.
			//
			// Measured 2026-05-25: statements 5.38%, branches 8.87%,
			//   functions 3.03%, lines 7.03%. Thresholds set 0.3-0.9 pp
			//   below to absorb minor float drift without flake.
			//
			// Tracked: Phase F coverage push — scaffold SvelteKit mock +
			//   add Storybook-backed test-storybook snapshot tests to
			//   push statements/lines back to ≥9% / ≥6%.
			thresholds: {
				statements: 5,
				branches: 8,
				functions: 3,
				lines: 6
			}
		}
	}
});
