import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';
import { defineConfig } from 'vitest/config';

// Mirrors the path aliases generated by SvelteKit in .svelte-kit/tsconfig.json.
// We can't inherit vite.config.ts (it uses the `sveltekit()` plugin which
// requires a full SvelteKit server context and crashes under Vitest 4).
// Instead we use the bare `svelte()` plugin and replicate aliases here.
const root = resolve(__dirname, 'src');

export default defineConfig({
	plugins: [svelte()],
	resolve: {
		alias: {
			$lib: resolve(root, 'lib'),
			'$lib/*': resolve(root, 'lib/*'),
			$features: resolve(root, 'lib/features'),
			'$features/*': resolve(root, 'lib/features/*'),
			$layouts: resolve(root, 'lib/layouts'),
			'$layouts/*': resolve(root, 'lib/layouts/*'),
			$ui: resolve(root, 'lib/components/ui'),
			'$ui/*': resolve(root, 'lib/components/ui/*'),
			$form: resolve(root, 'lib/components/form'),
			'$form/*': resolve(root, 'lib/components/form/*'),
			$icons: resolve(root, 'lib/icons'),
			'$icons/*': resolve(root, 'lib/icons/*'),
			$api: resolve(root, 'lib/api'),
			'$api/*': resolve(root, 'lib/api/*')
		}
	},
	test: {
		environment: 'jsdom',
		setupFiles: ['./tests/unit/setup.ts'],
		include: ['tests/unit/**/*.test.ts', 'src/**/*.test.ts'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html', 'lcov', 'json-summary'],
			reportsDirectory: './coverage',
			include: ['src/**/*.{ts,svelte}'],
			exclude: [
				'src/app.html',
				'src/app.d.ts',
				'src/hooks.client.ts',
				'src/lib/i18n/locales/**',
				'src/styles/**',
				'**/*.test.ts',
				'**/*.spec.ts'
			],
			// Coverage thresholds — ratcheted to measured floor after Phase E
			// high-value tests (hasCapability, useForm).
			// Measured 2026-05-19: statements 7.62%, branches 13.8%,
			//   functions 4.18%, lines 9.88%.
			// All below 20%: the codebase has ~4000 source lines; the unit
			// suite covers schemas/view-models/pure utils only. Svelte
			// components and TanStack query hooks require jsdom + SvelteKit
			// mock setup that isn't worth scaffolding until the E2E suite
			// covers the happy paths (tracked: Phase F coverage push).
			// TODO(Phase F): scaffold svelte-kit mock + add component tests
			//   to push statements/lines to ≥30%.
			thresholds: {
				statements: 7,
				branches: 13,
				functions: 4,
				lines: 9
			}
		}
	}
});
